import { DbUser, DbWasteType, DbCollectionPoint, DbEducationalTip, DbDiscard } from '../schemas/types';

export const SEED_USERS: DbUser[] = [
  {
    id: 'user-admin-1',
    nome: 'João Gestor SEMATUR',
    email: 'joao@gmail.com',
    senha_hash: '1234',
    perfil: 'admin',
    telefone: '(65) 3223-5500',
    cep: '78200-000',
    endereco: 'Rua Cel. José Dulce',
    numero: '500',
    bairro: 'Centro',
    cidade: 'Cáceres - MT',
    cargo: 'Secretário Municipal de Meio Ambiente',
    departamento: 'SEMATUR - Cáceres MT',
    bio: 'Gestão e monitoramento ambiental do município de Cáceres - MT.',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'user-cidadao-1',
    nome: 'Maria Cidadã Pantaneira',
    email: 'maria@gmail.com',
    senha_hash: '1234',
    perfil: 'cidadao',
    telefone: '(65) 99988-1234',
    cep: '78200-050',
    endereco: 'Rua Cel. Faria',
    numero: '210',
    bairro: 'Centro',
    cidade: 'Cáceres - MT',
    bio: 'Compromissada com a preservação do Pantanal e a reciclagem em Cáceres - MT.',
    criado_em: new Date().toISOString(),
  },
  {
    id: 'user-coletor-1',
    nome: 'Lucas Coletor COOPERCÁCERES',
    email: 'lucas@gmail.com',
    senha_hash: '1234',
    perfil: 'coletor',
    telefone: '(65) 99654-7890',
    cep: '78205-100',
    endereco: 'Av. Getúlio Vargas',
    numero: '1420',
    bairro: 'Santos Dumont',
    cidade: 'Cáceres - MT',
    veiculo: 'Caminhonete de Coleta Seletiva',
    capacidade_carga: '1.200 kg',
    bio: 'Coleta seletiva diária em Cáceres e suporte a cooperativas locais.',
    criado_em: new Date().toISOString(),
  },
];

export const SEED_WASTE_TYPES: DbWasteType[] = [
  { id: '1', nome: 'Plástico e PET', descricao: 'Garrafas PET, embalagens plásticas, potes e sacolas limpas.' },
  { id: '2', nome: 'Papel e Papelão', descricao: 'Caixas de papelão desmontadas, jornais, folhas e revistas secas.' },
  { id: '3', nome: 'Vidro', descricao: 'Garrafas, potes de conserva e recipientes de vidro intactos.' },
  { id: '4', nome: 'Metal e Alumínio', descricao: 'Latas de bebidas, tampas de metal, panelas velhas e arames.' },
  { id: '5', nome: 'Eletrônicos e Baterias', descricao: 'Celulares antigos, cabos, pilhas, carregadores e periféricos.' },
  { id: '6', nome: 'Óleo de Cozinha Usado', descricao: 'Óleo vegetal usado acondicionado em garrafas PET bem vedadas.' },
];

export const SEED_COLLECTION_POINTS: DbCollectionPoint[] = [
  {
    id: '1',
    nome: 'Ecoponto Central - Praça Barão',
    cep: '78200-000',
    endereco: 'Rua Cel. José Dulce',
    numero: '100',
    bairro: 'Centro',
    cidade: 'Cáceres',
    estado: 'MT',
    residuos_aceitos: 'Plástico, Papel, Papelão, Vidro e Metal',
    horario: 'Segunda a Sexta, das 07h30 às 17h30',
    latitude: -16.0725,
    longitude: -57.6798,
  },
  {
    id: '2',
    nome: 'Cooperativa dos Catadores (COOPERCÁCERES)',
    cep: '78205-100',
    endereco: 'Av. Getúlio Vargas',
    numero: '1420',
    bairro: 'Santos Dumont',
    cidade: 'Cáceres',
    estado: 'MT',
    residuos_aceitos: 'Todos os recicláveis, Papelão, PET, Sucata e Prensados',
    horario: 'Segunda a Sábado, das 07h às 17h',
    latitude: -16.085,
    longitude: -57.6912,
  },
  {
    id: '3',
    nome: 'Ecoponto Bairro Cavalhada',
    cep: '78202-000',
    endereco: 'Rua dos Lavradores',
    numero: '350',
    bairro: 'Cavalhada',
    cidade: 'Cáceres',
    estado: 'MT',
    residuos_aceitos: 'Plástico, Vidro e Óleo de Cozinha Usado',
    horario: 'Segunda a Sexta, das 08h às 16h',
    latitude: -16.0645,
    longitude: -57.672,
  },
  {
    id: '4',
    nome: 'Ecoponto Cohab Nova',
    cep: '78208-200',
    endereco: 'Av. dos Imigrantes',
    numero: 's/n',
    bairro: 'Cohab Nova',
    cidade: 'Cáceres',
    estado: 'MT',
    residuos_aceitos: 'Eletrônicos, Pilhas, Baterias, Metais e Papel',
    horario: 'Segunda a Sábado, das 08h às 17h',
    latitude: -16.091,
    longitude: -57.665,
  },
  {
    id: '5',
    nome: 'PEV Jardim Guanabara (Campus UNEMAT)',
    cep: '78206-000',
    endereco: 'Av. Tancredo Neves',
    numero: '800',
    bairro: 'Jardim Guanabara',
    cidade: 'Cáceres',
    estado: 'MT',
    residuos_aceitos: 'Papel, Papelão, Plástico e Lixo Eletrônico',
    horario: 'Segunda a Sexta, das 07h às 21h',
    latitude: -16.058,
    longitude: -57.689,
  },
  {
    id: '6',
    nome: 'Ponto Ecológico DNER',
    cep: '78207-000',
    endereco: 'Rua das Violetas',
    numero: '210',
    bairro: 'DNER',
    cidade: 'Cáceres',
    estado: 'MT',
    residuos_aceitos: 'Plástico, Metal, Papelão e Óleo',
    horario: 'Segunda a Sexta, das 08h às 17h',
    latitude: -16.0815,
    longitude: -57.684,
  },
];

export const SEED_EDUCATIONAL_TIPS: DbEducationalTip[] = [
  {
    id: '1',
    titulo: 'Proteja as Águas do Rio Paraguai',
    categoria: 'Preservação Pantanal',
    conteudo: 'O descarte correto de materiais recicláveis em Cáceres impede que resíduos plásticos cheguem ao leito do Rio Paraguai, protegendo a rica fauna pantaneira.',
  },
  {
    id: '2',
    titulo: 'Descarte Correto do Óleo de Cozinha',
    categoria: 'Recursos Hídricos',
    conteudo: '1 litro de óleo pode poluir até 25 mil litros de água. Guarde o óleo frio em garrafas PET e entregue nos ecopontos da Cavalhada ou COOPERCÁCERES.',
  },
  {
    id: '3',
    titulo: 'Separação para a COOPERCÁCERES',
    categoria: 'Apoio aos Catadores',
    conteudo: 'Enxaguar embalagens de leite e potes de plástico facilita o trabalho diário dos catadores da Cooperativa de Cáceres e valoriza a reciclagem local.',
  },
  {
    id: '4',
    titulo: 'Pilhas e Eletrônicos no PEV Cohab Nova',
    categoria: 'Lixo Eletrônico',
    conteudo: 'Metais pesados como chumbo e mercúrio contaminam o solo de Cáceres. Descarte celulares velhos, cabos e pilhas no PEV Cohab Nova ou na UNEMAT.',
  },
  {
    id: '5',
    titulo: 'Compostagem Doméstica de Orgânicos',
    categoria: 'Sustentabilidade',
    conteudo: 'Separe cascas de frutas e sobras de vegetais para adubação natural, reduzindo o volume de matéria orgânica enviada aos aterros municipais.',
  },
  {
    id: '6',
    titulo: 'Logística Reversa de Embalagens e Vidros',
    categoria: 'Economia Circular',
    conteudo: 'Garrafas e recipientes de vidro devem ser limpos e acondicionados com segurança para facilitar o recolhimento pelos catadores sem risco de acidentes.',
  },
];

export const SEED_DISCARDS: DbDiscard[] = [];